server:
  port: 8081

spring:
  application:
    name: account-service
  jackson:
    serialization:
      indent-output: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/threerivers;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
#    username: sa
#    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
        generate_statistics: false
        jdbc:
          time_zone: UTC
  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://localhost:8761/eureka/

logging:
  level:
    root: error
    org.springframework: info
    org.hibernate: info
    org.hibernate.stat: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    com.rivers.account.: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'